const fs=require('fs');const path=require('path');const root=path.resolve(__dirname,'..');const required=['index.html','styles.css','import.css','data.js','app.js','manifest.webmanifest','service-worker.js','README.md','api/rewe-prices.js'];for(const f of required){if(!fs.existsSync(path.join(root,f)))throw new Error('Fehlt: '+f)}const html=fs.readFileSync(path.join(root,'index.html'),'utf8');if (!html.includes('AKTUELLER SPARPLAN')) {
  throw new Error('Einkaufsreiter muss den aktuellen Sparplan anzeigen');
}
if (html.includes('Automatisch aus der ausgewählten Vorlagenwoche erstellt')) {
  throw new Error('Einkaufsreiter darf keine Vorlagenliste ankündigen');
}
if (html.includes('id="importPrices"') || html.includes('id="priceFile"')) {
  throw new Error('Alter Vorlagenpreis-Import darf im Einkaufsreiter nicht erscheinen');
}
for(const ref of ['styles.css','import.css','data.js','app.js'])if(!html.includes(ref))throw new Error('Referenz fehlt: '+ref);for(const id of ['weekendPlan','nextWeekPlan','sourceStatus','marketRecommendation','runWeeklyPlan','rerollPlan','dietaryExclusions','applyExclusions','importReweHtml','importEdekaHtml','retailerHtmlFile','prepTitle','prepSummary'])if(!html.includes(`id="${id}"`))throw new Error('Planungsbereich fehlt: '+id);const data=fs.readFileSync(path.join(root,'data.js'),'utf8');if(!data.includes('window.KOCHBUCH_DATA'))throw new Error('Datenobjekt fehlt');for(const recipe of ['frosta-evening','mexico-pork','spinach-pasta','leberkaese-eggs','pesto-pea-pasta','vegetable-egg-rice','spinach-tortellini','chicken-potato-pan'])if(!data.includes(`"id": "${recipe}"`))throw new Error('Angebotsrezept fehlt: '+recipe);if(data.includes('"id": "schlemmer-fish"'))throw new Error('Fischrezept darf nicht enthalten sein');const app=fs.readFileSync(path.join(root,'app.js'),'utf8');if(app.includes('Liveabruf nicht verbunden'))throw new Error('Veraltete Liveabruf-Meldung darf nicht erscheinen');if(!app.includes('r.seasoningTip'))throw new Error('Rezeptdialog muss die Gewürzempfehlung aus dem Rezept rendern');if(!html.includes('Quellenstatus prüfen'))throw new Error('Einkaufsansicht muss den echten Quellenstatus prüfen');const worker=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');if(!worker.includes("const CACHE = 'kochbuch-v14';")||!worker.includes("pathname.startsWith('/api/')"))throw new Error('Service Worker muss API-Antworten frisch laden und Cache-Version v14 verwenden');for(const asset of ['./recipe-seasonings.js','./recipe-expansion.js'])if(!worker.includes(asset))throw new Error('Service-Worker-Cache fehlt: '+asset);console.log('Website-Struktur OK');
